import logging
from datetime import datetime
from bson import ObjectId
from flask import Blueprint, request, jsonify, g

from database import get_db
from utils.auth_middleware import authenticate_token
from services.audit_service import log_audit
from utils.tzutils import utc_now, to_iso_string

logger = logging.getLogger(__name__)

expenses_bp = Blueprint('expenses', __name__)

@expenses_bp.route('/', methods=['GET'])
@authenticate_token
def get_expenses():
    db = get_db()
    expenses = db.expenses.find().sort("date", -1)
    
    formatted = []
    for e in expenses:
        formatted.append({
            "id": str(e['_id']),
            "description": e.get('description'),
            "amount": e.get('amount'),
            "category": e.get('category'),
            "date": e.get('date').isoformat() if isinstance(e.get('date'), datetime) else str(e.get('date')),
            "createdBy": e.get('createdBy'),
            "createdByUsername": e.get('createdByUsername'),
            "autoGenerated": e.get('autoGenerated', False),
            "productId": str(e.get('productId')) if e.get('productId') else None,
            "productName": e.get('productName')
        })
    
    return jsonify(formatted)

@expenses_bp.route('/', methods=['POST'])
@authenticate_token
def add_expense():
    data = request.get_json()
    description = data.get('description', '').strip()
    amount = data.get('amount')
    category = data.get('category', 'General')
    
    # client time vs server time
    date_str = data.get('date')
    expense_date = utc_now()
    if date_str:
        try:
            from dateutil import parser
            expense_date = parser.parse(date_str)
        except Exception:
            pass

    user_id = g.user.get('userId')
    username = g.user.get('username', 'Unknown')

    if not description or amount is None:
        return jsonify({"error": "Description and amount are required"}), 400

    try:
        amount = float(amount)
    except ValueError:
        return jsonify({"error": "Invalid amount"}), 400

    db = get_db()
    
    expense = {
        "description": description,
        "amount": amount,
        "category": category,
        "date": expense_date,
        "createdAt": utc_now(),
        "createdBy": user_id,
        "createdByUsername": username
    }
    
    result = db.expenses.insert_one(expense)
    
    log_audit(db, "EXPENSE_ADDED", user_id, username, {
        "expenseId": str(result.inserted_id),
        "description": description,
        "amount": amount
    })
    
    expense['id'] = str(result.inserted_id)
    expense['date'] = expense['date'].isoformat()
    expense['createdAt'] = expense['createdAt'].isoformat()
    if '_id' in expense:
        del expense['_id']
        
    return jsonify(expense)

@expenses_bp.route('/<id>', methods=['DELETE'])
@authenticate_token
def delete_expense(id):
    user_id = g.user.get('userId')
    username = g.user.get('username', 'Unknown')
    db = get_db()
    
    expense = db.expenses.find_one({"_id": ObjectId(id)})
    if not expense:
        return jsonify({"error": "Expense not found"}), 404
        
    db.expenses.delete_one({"_id": ObjectId(id)})
    
    log_audit(db, "EXPENSE_DELETED", user_id, username, {
        "expenseId": id,
        "description": expense.get('description'),
        "amount": expense.get('amount')
    })
    
    return jsonify({"success": True})
