import logging
import re
from datetime import datetime
from bson import ObjectId
from flask import Blueprint, request, jsonify, redirect, g

from database import get_db
from utils.auth_middleware import authenticate_token, require_admin
from services.audit_service import log_audit
from services.barcode_service import generate_product_barcode, generate_barcode_image, generate_qr_code
from services.cloudinary_service import upload_product_photo, delete_cloudinary_asset, is_configured

logger = logging.getLogger(__name__)

products_bp = Blueprint('products', __name__)

@products_bp.route('/', methods=['GET'])
@authenticate_token
def get_products():
    db = get_db()
    
    page = max(1, int(request.args.get('page', 1)))
    limit = min(max(1, int(request.args.get('limit', 500))), 1000)
    skip = (page - 1) * limit
    search = request.args.get('search', '').strip()

    filter_query = {}
    if search:
        regex = re.compile(search, re.IGNORECASE)
        filter_query = {
            "$or": [
                {"name": regex},
                {"barcode": regex},
                {"hsnCode": regex}
            ]
        }

    products_cursor = db.products.find(filter_query).sort("name", 1).skip(skip).limit(limit)
    total = db.products.count_documents(filter_query)

    formatted = []
    for p in products_cursor:
        try:
            cost_price = float(p.get('costPrice', 0) or 0)
        except (ValueError, TypeError):
            cost_price = 0.0
            
        try:
            price = float(p.get('price', 0) or 0)
        except (ValueError, TypeError):
            price = 0.0
            
        try:
            quantity = int(p.get('quantity', 0) or 0)
        except (ValueError, TypeError):
            quantity = 0

        try:
            gst_percent = float(p.get('gstPercent', 18) or 18)
        except (ValueError, TypeError):
            gst_percent = 18.0

        gst_factor = 1 + (gst_percent / 100.0)
        base_price = price / gst_factor if price > 0 else 0
        
        profit = base_price - cost_price
        # Margin calculated against cost price as per standard UI
        profit_percent = round(((profit / cost_price) * 100), 2) if cost_price > 0 else 0

        formatted.append({
            "id": str(p['_id']),
            "_id": str(p['_id']),
            "name": p.get('name'),
            "quantity": quantity,
            "price": price,
            "costPrice": cost_price,
            "gstPercent": gst_percent,
            "hsnCode": p.get('hsnCode', '9999'),
            "minStock": p.get('minStock', 10),
            "barcode": p.get('barcode'),
            "photo": p.get('photo'),
            "photos": p.get('photos', []),
            "profit": profit,
            "profitPercent": profit_percent
        })

    response = jsonify(formatted)
    response.headers['X-Total-Count'] = str(total)
    return response

@products_bp.route('/', methods=['POST'])
@authenticate_token
def add_product():
    data = request.get_json()
    name = data.get('name', '').strip()
    quantity = int(data.get('quantity') or 0)
    price = float(data.get('price') or 0)
    cost_price = float(data.get('costPrice') or 0)
    gst_percent = float(data.get('gstPercent') or 18)
    hsn_code = data.get('hsnCode', '9999')
    min_stock = int(data.get('minStock') or 10)

    user_id = g.user.get('userId')
    username = g.user.get('username', 'Unknown')

    if not name or price < 0:
        return jsonify({"error": "Invalid product name or price"}), 400

    db = get_db()
    
    product = {
        "name": name,
        "quantity": quantity,
        "price": price,
        "costPrice": cost_price,
        "gstPercent": gst_percent,
        "hsnCode": hsn_code,
        "minStock": min_stock,
        "barcode": None,
        "photo": None,
        "photos": [],
        "createdAt": datetime.utcnow(),
        "createdBy": user_id,
        "createdByUsername": username
    }

    result = db.products.insert_one(product)
    product_id = str(result.inserted_id)

    # Auto generate barcode
    barcode_value = generate_product_barcode(name, product_id)
    db.products.update_one({"_id": result.inserted_id}, {"$set": {"barcode": barcode_value}})

    # Auto-create expense
    if quantity > 0 and cost_price > 0:
        total_cost = quantity * cost_price
        db.expenses.insert_one({
            "description": f"Product Purchase: {name} ({quantity} units x Rs{cost_price})",
            "amount": total_cost,
            "category": "Supplies",
            "date": datetime.utcnow(),
            "createdAt": datetime.utcnow(),
            "createdBy": user_id,
            "createdByUsername": username,
            "autoGenerated": True,
            "productId": product_id,
            "productName": name
        })

    log_audit(db, "PRODUCT_ADDED", user_id, username, {
        "productId": product_id,
        "productName": name,
        "barcode": barcode_value,
        "quantity": quantity,
        "price": price
    })

    return jsonify({
        "id": product_id,
        "name": name,
        "quantity": quantity,
        "price": price,
        "costPrice": cost_price,
        "gstPercent": gst_percent,
        "hsnCode": hsn_code,
        "barcode": barcode_value
    })

@products_bp.route('/<id>', methods=['PATCH'])
@authenticate_token
def update_stock(id):
    data = request.get_json()
    new_quantity = int(data.get('quantity') or 0)
    user_id = g.user.get('userId')
    username = g.user.get('username')

    db = get_db()
    product = db.products.find_one({"_id": ObjectId(id)})
    if not product:
        return jsonify({"error": "Product not found"}), 404

    try:
        old_quantity = int(product.get('quantity', 0) or 0)
    except (ValueError, TypeError):
        old_quantity = 0
    
    db.products.update_one(
        {"_id": ObjectId(id)},
        {"$set": {
            "quantity": new_quantity,
            "lastModifiedBy": user_id,
            "lastModifiedByUsername": username,
            "lastModified": datetime.utcnow()
        }}
    )

    # Restock expense
    added_qty = new_quantity - old_quantity
    try:
        cost_price = float(product.get('costPrice', 0) or 0)
    except (ValueError, TypeError):
        cost_price = 0.0
        
    if added_qty > 0 and cost_price > 0:
        db.expenses.insert_one({
            "description": f"Restock: {product.get('name')} (+{added_qty} units x Rs{cost_price})",
            "amount": added_qty * cost_price,
            "category": "Supplies",
            "date": datetime.utcnow(),
            "createdAt": datetime.utcnow(),
            "createdBy": user_id,
            "createdByUsername": username,
            "autoGenerated": True,
            "productId": id,
            "productName": product.get('name')
        })

    log_audit(db, "PRODUCT_STOCK_UPDATED", user_id, username, {
        "productId": id,
        "productName": product.get('name'),
        "oldQuantity": old_quantity,
        "newQuantity": new_quantity,
        "change": added_qty
    })

    return jsonify({"success": True})

@products_bp.route('/<id>', methods=['PUT'])
@authenticate_token
def full_update_product(id):
    data = request.get_json()
    name = data.get('name', '').strip()
    quantity = int(data.get('quantity') or 0)
    price = float(data.get('price') or 0)
    cost_price = float(data.get('costPrice') or 0)
    gst_percent = float(data.get('gstPercent') or 18)
    hsn_code = data.get('hsnCode', '9999')
    min_stock = int(data.get('minStock') or 10)
    barcode = data.get('barcode')

    user_id = g.user.get('userId')
    username = g.user.get('username')

    db = get_db()
    old_product = db.products.find_one({"_id": ObjectId(id)})
    if not old_product:
        return jsonify({"error": "Product not found"}), 404

    update_data = {
        "name": name,
        "quantity": quantity,
        "price": price,
        "costPrice": cost_price,
        "gstPercent": gst_percent,
        "hsnCode": hsn_code,
        "minStock": min_stock,
        "lastModifiedBy": user_id,
        "lastModifiedByUsername": username,
        "lastModified": datetime.utcnow()
    }
    if barcode:
        update_data['barcode'] = barcode

    db.products.update_one({"_id": ObjectId(id)}, {"$set": update_data})

    # Restock expense
    try:
        old_qty = int(old_product.get('quantity', 0) or 0)
    except (ValueError, TypeError):
        old_qty = 0
        
    added_qty = quantity - old_qty
    if added_qty > 0 and cost_price > 0:
        db.expenses.insert_one({
            "description": f"Restock: {name} (+{added_qty} units x Rs{cost_price})",
            "amount": added_qty * cost_price,
            "category": "Supplies",
            "date": datetime.utcnow(),
            "createdAt": datetime.utcnow(),
            "createdBy": user_id,
            "createdByUsername": username,
            "autoGenerated": True,
            "productId": id,
            "productName": name
        })

    log_audit(db, "PRODUCT_UPDATED", user_id, username, {"productId": id, "productName": name})
    return jsonify({"success": True})

@products_bp.route('/<id>', methods=['DELETE'])
@authenticate_token
@require_admin
def delete_product(id):
    user_id = g.user.get('userId')
    username = g.user.get('username')
    db = get_db()
    product = db.products.find_one({"_id": ObjectId(id)})
    
    if not product:
        return jsonify({"error": "Product not found"}), 404

    # Delete all specific photos mapping to this product
    for photo in product.get('photos', []):
        if photo.get('storage') == 'cloudinary' and photo.get('cloudinaryPublicId'):
            delete_cloudinary_asset(photo['cloudinaryPublicId'])
            
    if product.get('cloudinaryPublicId'):
        delete_cloudinary_asset(product['cloudinaryPublicId'])
        
    db.products.delete_one({"_id": ObjectId(id)})

    log_audit(db, "PRODUCT_DELETED", user_id, username, {"productId": id, "productName": product.get('name')})
    return jsonify({"success": True})

@products_bp.route('/barcode/<barcode>', methods=['GET'])
@authenticate_token
def search_barcode(barcode):
    db = get_db()
    regex = re.compile(barcode, re.IGNORECASE)
    product = db.products.find_one({
        "$or": [
            {"barcode": barcode},
            {"sku": barcode},
            {"name": regex}
        ]
    })
    
    if not product:
        return jsonify({"error": "Product not found"}), 404
        
    return jsonify({
        "id": str(product['_id']),
        "name": product.get('name'),
        "price": product.get('price', 0),
        "costPrice": product.get('costPrice', 0),
        "quantity": product.get('quantity', 0),
        "barcode": product.get('barcode'),
        "photo": product.get('photo')
    })

@products_bp.route('/<id>/barcode', methods=['GET'])
@authenticate_token
def get_barcode_image(id):
    fmt = request.args.get('format', 'image')
    db = get_db()
    product = db.products.find_one({"_id": ObjectId(id)})
    
    if not product:
        return jsonify({"error": "Product not found"}), 404
        
    barcode_value = product.get('barcode') or generate_product_barcode(product.get('name'), id)
    
    try:
        if fmt == 'qr':
            qr_data = {
                "id": id,
                "name": product.get('name'),
                "barcode": barcode_value,
                "price": product.get('price')
            }
            img = generate_qr_code(qr_data)
            return jsonify({"barcode": barcode_value, "qrCode": img})
        else:
            img = generate_barcode_image(barcode_value)
            return jsonify({"barcode": barcode_value, "image": img})
    except Exception as e:
        return jsonify({"error": str(e)}), 500

@products_bp.route('/<id>/photo', methods=['POST'])
@authenticate_token
def upload_photo(id):
    if 'photo' not in request.files:
        return jsonify({"error": "No photo file uploaded"}), 400
        
    if not is_configured():
        return jsonify({"error": "Cloudinary storage not configured"}), 503
        
    file = request.files['photo']
    if file.filename == '':
        return jsonify({"error": "Empty filename"}), 400
        
    user_id = g.user.get('userId')
    username = g.user.get('username')
    db = get_db()
    
    product = db.products.find_one({"_id": ObjectId(id)})
    if not product:
        return jsonify({"error": "Product not found"}), 404
        
    try:
        result = upload_product_photo(file, id)
        photo_url = result['url']
        public_id = result['publicId']
        
        photo_entry = {
            "id": public_id,
            "url": photo_url,
            "storage": "cloudinary",
            "cloudinaryPublicId": public_id,
            "filename": file.filename,
            "uploadedAt": datetime.utcnow(),
            "uploadedBy": user_id,
            "uploadedByUsername": username
        }
        
        db.products.update_one(
            {"_id": ObjectId(id)},
            {
                "$push": {"photos": photo_entry},
                "$set": {
                    "photo": photo_url,
                    "lastModifiedBy": user_id,
                    "lastModifiedByUsername": username,
                    "lastModified": datetime.utcnow()
                }
            }
        )
        
        log_audit(db, "PRODUCT_PHOTO_UPLOADED", user_id, username, {
            "productId": id, "productName": product.get('name'), "cloudinaryPublicId": public_id
        })
        
        return jsonify({
            "success": True, 
            "photo": {
                "id": public_id,
                "url": photo_url,
                "storage": "cloudinary"
            },
            "message": "Product photo uploaded successfully"
        })
    except Exception as e:
        logger.error(f"Failed photo upload: {e}")
        return jsonify({"error": str(e)}), 500

@products_bp.route('/<id>/photo', methods=['GET'])
def get_photo(id):
    db = get_db()
    product = db.products.find_one({"_id": ObjectId(id)})
    
    if not product:
        return jsonify({"error": "Product not found"}), 404
        
    photo_url = product.get('photo')
    if photo_url and photo_url.startswith('http'):
        return redirect(photo_url, code=302)
        
    return jsonify({"error": "Legacy file-system photos are not migrated to Python server. Please reupload."}), 404

@products_bp.route('/<id>/photo/<photo_id>', methods=['DELETE'])
@authenticate_token
def delete_photo(id, photo_id):
    confirmed = request.args.get('confirmed')
    if confirmed != 'true':
        return jsonify({"error": "Photo deletion requires explicit confirmation (?confirmed=true)"}), 400
        
    user_id = g.user.get('userId')
    username = g.user.get('username')
    db = get_db()
    
    product = db.products.find_one({"_id": ObjectId(id)})
    if not product:
        return jsonify({"error": "Product not found"}), 404
        
    photo_target = None
    for p in product.get('photos', []):
        if p.get('id') == photo_id or p.get('cloudinaryPublicId') == photo_id:
            photo_target = p
            break
            
    if not photo_target:
        return jsonify({"error": "Photo not found"}), 404

    if photo_target.get('storage') == 'cloudinary' and photo_target.get('cloudinaryPublicId'):
        delete_cloudinary_asset(photo_target['cloudinaryPublicId'])

    db.products.update_one(
        {"_id": ObjectId(id)},
        {
            "$pull": {"photos": {"id": photo_target.get('id', photo_id)}},
            "$set": {
                "lastModifiedBy": user_id,
                "lastModifiedByUsername": username,
                "lastModified": datetime.utcnow()
            }
        }
    )
    
    log_audit(db, "PRODUCT_PHOTO_DELETED", user_id, username, {"productId": id, "photoId": photo_id})
    return jsonify({"success": True, "message": "Photo deleted successfully", "photoId": photo_id})
