import React, { useState, useEffect } from 'react';
import DateRangeSelector from './DateRangeSelector';
import Icon from '../../Icon';
import { formatCurrency0, formatCurrency } from '../../constants';
import { API, getAuthHeaders } from '../../utils/api';

export default function Reports({
  invoices,
  products,
  customers,
  canViewProfit
}) {
  const [startDate, setStartDate] = useState('');
  const [endDate, setEndDate] = useState('');
  const [financialSummary, setFinancialSummary] = useState(null);
  const [operatingExpenses, setOperatingExpenses] = useState([]);
  const [loading, setLoading] = useState(false);

  const filteredInvoices = invoices.filter(inv => {
    if (!startDate || !endDate) return true;
    const invDate = new Date(inv.createdAt || inv.date);
    return invDate >= new Date(startDate) && invDate <= new Date(endDate);
  });

  // Fetch comprehensive financial summary from backend
  useEffect(() => {
    const fetchData = async () => {
      setLoading(true);
      try {
        // Calculate days for the API call
        let days = 30;
        if (startDate && endDate) {
          const start = new Date(startDate);
          const end = new Date(endDate);
          days = Math.ceil((end - start) / (1000 * 60 * 60 * 24));
        }

        // Fetch financial summary
        const res = await fetch(API(`/api/analytics/financial-summary?days=${days}`), {
          headers: {
            ...getAuthHeaders(),
            'Content-Type': 'application/json'
          }
        });

        if (res.ok) {
          const data = await res.json();

          // Normalize response to handle both old and new API response structures
          const normalizedData = {
            ...data,
            sales: data.sales || {
              totalSales: data.revenue?.totalRevenue || 0,
              totalReturns: 0,
              netRevenue: data.revenue?.baseRevenue || 0
            },
            costs: data.costs || {
              totalCogs: data.costs?.cogs || 0,
              totalReturnCost: 0,
              netCogs: data.costs?.cogs || 0
            },
            profitSummary: {
              ...data.profitSummary,
              netProfit: data.profitSummary?.netProfit || data.netProfit?.netProfit || data.profitSummary?.grossProfit || 0,
              netProfitMargin: data.profitSummary?.netProfitMargin || data.netProfit?.netProfitMargin || 0
            }
          };

          setFinancialSummary(normalizedData);
        } else {
          console.warn('Failed to fetch financial summary');
        }

        // Fetch operating expenses breakdown
        const expRes = await fetch(API('/api/expenses'), {
          headers: {
            ...getAuthHeaders(),
            'Content-Type': 'application/json'
          }
        });

        if (expRes.ok) {
          const data = await expRes.json();
          let filtered = data.filter(e => e.expenseType !== 'inventory' && !e.autoGenerated);

          if (startDate || endDate) {
            filtered = filtered.filter(e => {
              const d = new Date(e.date);
              if (startDate && d < new Date(startDate)) return false;
              if (endDate && d > new Date(endDate)) return false;
              return true;
            });
          }
          setOperatingExpenses(filtered);
        }
      } catch (err) {
        console.error('Failed to fetch financial data:', err);
      } finally {
        setLoading(false);
      }
    };

    fetchData();
  }, [startDate, endDate]);

  // Payment tracking (EMI-aware)
  const paymentSummary = filteredInvoices.reduce((acc, inv) => {
    const grandTotal = inv.grandTotal || inv.total || 0;
    const paymentMode = (inv.paymentMode || 'cash').toLowerCase();

    if (paymentMode === 'emi' && inv.emiDetails) {
      const downPayment = inv.emiDetails.downPayment || 0;
      acc.collected += downPayment;
      acc.pending += (grandTotal - downPayment);
      acc.emiCount += 1;
    } else {
      acc.collected += grandTotal;
    }

    return acc;
  }, { collected: 0, pending: 0, emiCount: 0 });

  // Group expenses by category for operating expenses section
  const expensesByCategory = operatingExpenses.reduce((acc, exp) => {
    const category = exp.category || 'Other';
    if (!acc[category]) {
      acc[category] = 0;
    }
    acc[category] += exp.amount || 0;
    return acc;
  }, {});

  const reportData = {
    period: startDate && endDate ? `${startDate} to ${endDate}` : 'All Time',
    totalInvoices: filteredInvoices.length,
    totalProducts: products.length,
    totalCustomers: customers.length,
    lowStockCount: products.filter(p => p.quantity < (p.minStock || 20)).length,
    paymentSummary
  };

  return (
    <div className="reports">
      <div className="reports-header">
        <div>
          <h2 className="reports-title">📈 Reports</h2>
          <p className="reports-subtitle">Generate and export business reports</p>
        </div>
      </div>

      <DateRangeSelector
        startDate={startDate}
        endDate={endDate}
        onStartDateChange={setStartDate}
        onEndDateChange={setEndDate}
      />

      {/* SECTION 1: PROFIT SUMMARY WITH RETURNS ADJUSTMENTS */}
      {canViewProfit && financialSummary && (
        <div className="report-summary">
          <h3>💰 Profit Summary</h3>
          <div className="summary-grid">
            <div className="summary-item">
              <Icon name="dollar-sign" size={24} />
              <div>
                <span>Total Sales (incl GST)</span>
                <strong>{formatCurrency0(financialSummary?.sales?.totalSales || financialSummary?.revenue?.totalRevenue || 0)}</strong>
                <small style={{ color: '#64748b', fontSize: '11px' }}>Gross revenue</small>
              </div>
            </div>

            {/* Returns Adjustment - Show if there are returns */}
            {(financialSummary?.sales?.totalReturns || 0) > 0 && (
              <div className="summary-item" style={{ color: '#ef4444' }}>
                <Icon name="arrow-down" size={24} />
                <div>
                  <span>Returns & Refunds</span>
                  <strong>-{formatCurrency0(financialSummary?.sales?.totalReturns || 0)}</strong>
                  <small style={{ color: '#64748b', fontSize: '11px' }}>Refunded to customers</small>
                </div>
              </div>
            )}

            <div className="summary-item" style={{ color: '#3b82f6', fontWeight: 600 }}>
              <Icon name="dollar-sign" size={24} />
              <div>
                <span>Net Revenue (excl GST)</span>
                <strong>{formatCurrency0(financialSummary?.sales?.netRevenue || financialSummary?.revenue?.baseRevenue || 0)}</strong>
                <small style={{ color: '#64748b', fontSize: '11px' }}>After returns & GST</small>
              </div>
            </div>

            <div className="summary-item">
              <Icon name="shopping-cart" size={24} />
              <div>
                <span>Product Cost (COGS)</span>
                <strong>{formatCurrency0(financialSummary?.costs?.totalCogs || 0)}</strong>
                <small style={{ color: '#64748b', fontSize: '11px' }}>Cost price of sold items</small>
              </div>
            </div>

            {/* Return Costs Adjustment - Show if there are returns */}
            {(financialSummary?.costs?.totalReturnCost || 0) > 0 && (
              <div className="summary-item" style={{ color: '#10b981' }}>
                <Icon name="arrow-up" size={24} />
                <div>
                  <span>Return Costs Recovered</span>
                  <strong>-{formatCurrency0(financialSummary?.costs?.totalReturnCost || 0)}</strong>
                  <small style={{ color: '#64748b', fontSize: '11px' }}>Cost saved from returns</small>
                </div>
              </div>
            )}

            <div className="summary-item" style={{ color: '#3b82f6', fontWeight: 600 }}>
              <Icon name="shopping-cart" size={24} />
              <div>
                <span>Net COGS (after returns)</span>
                <strong>{formatCurrency0(financialSummary?.costs?.netCogs || 0)}</strong>
                <small style={{ color: '#64748b', fontSize: '11px' }}>Adjusted for returns</small>
              </div>
            </div>

            <div className="summary-item" style={{ color: '#10b981' }}>
              <Icon name="trending-up" size={24} />
              <div>
                <span>Gross Profit</span>
                <strong>{formatCurrency0(financialSummary?.profitSummary?.grossProfit || 0)}</strong>
                <small style={{ color: '#64748b', fontSize: '11px' }}>
                  {financialSummary?.profitSummary?.grossProfitMargin || 0}% margin
                </small>
              </div>
            </div>

            <div className="summary-item" style={{
              color: (financialSummary?.profitSummary?.netProfit || 0) >= 0 ? '#10b981' : '#ef4444'
            }}>
              <Icon name="trending-up" size={24} />
              <div>
                <span>Net Profit</span>
                <strong>{formatCurrency0(financialSummary?.profitSummary?.netProfit || 0)}</strong>
                <small style={{ color: '#64748b', fontSize: '11px' }}>
                  {financialSummary?.profitSummary?.netProfitMargin || 0}% margin
                </small>
              </div>
            </div>

            <div className="summary-item">
              <Icon name="percent" size={24} />
              <div>
                <span>GST Collected</span>
                <strong>{formatCurrency0(financialSummary?.revenue?.gstCollected || 0)}</strong>
                <small style={{ color: '#64748b', fontSize: '11px' }}>To government</small>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* SECTION 2: OPERATING EXPENSES BREAKDOWN */}
      {canViewProfit && operatingExpenses.length > 0 && (
        <div className="report-summary" style={{ marginTop: '24px' }}>
          <h3>🏢 Operating Expenses</h3>
          <div className="summary-grid">
            {Object.entries(expensesByCategory).map(([category, amount]) => (
              <div key={category} className="summary-item">
                <Icon name="credit-card" size={24} />
                <div>
                  <span>{category}</span>
                  <strong>{formatCurrency0(amount)}</strong>
                  <small style={{ color: '#64748b', fontSize: '11px' }}>
                    {((amount / (financialSummary?.operatingExpenses?.total || 1)) * 100).toFixed(1)}% of total
                  </small>
                </div>
              </div>
            ))}
            <div className="summary-item" style={{ color: '#f59e0b' }}>
              <Icon name="credit-card" size={24} />
              <div>
                <span>Total Operating Expenses</span>
                <strong>{formatCurrency0(financialSummary?.operatingExpenses.total || 0)}</strong>
                <small style={{ color: '#64748b', fontSize: '11px' }}>Salary, Rent, Utilities, etc.</small>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* SECTION 3: TOTAL EXPENSES OVERVIEW (NEW) */}
      {canViewProfit && financialSummary && (
        <div className="report-summary" style={{ marginTop: '24px' }}>
          <h3>📊 Total Expenses Overview</h3>
          <div className="summary-grid">
            <div className="summary-item">
              <Icon name="shopping-cart" size={24} />
              <div>
                <span>COGS (Cost of Goods Sold)</span>
                <strong>{formatCurrency0(financialSummary.totalExpenses.cogs)}</strong>
                <small style={{ color: '#64748b', fontSize: '11px' }}>From product sales</small>
              </div>
            </div>

            <div className="summary-item">
              <Icon name="building" size={24} />
              <div>
                <span>Operating Expenses</span>
                <strong>{formatCurrency0(financialSummary.totalExpenses.operatingExpenses)}</strong>
                <small style={{ color: '#64748b', fontSize: '11px' }}>Salary, Rent, Utilities</small>
              </div>
            </div>

            <div className="summary-item" style={{ color: '#ef4444' }}>
              <Icon name="alert-circle" size={24} />
              <div>
                <span>Total Expenses</span>
                <strong>{formatCurrency0(financialSummary.totalExpenses.total)}</strong>
                <small style={{ color: '#64748b', fontSize: '11px' }}>COGS + Operating</small>
              </div>
            </div>

            <div className="summary-item">
              <Icon name="info" size={24} />
              <div>
                <span>Formula</span>
                <strong>Base Revenue - Total Expenses</strong>
                <small style={{ color: '#64748b', fontSize: '11px' }}>
                  ₹{formatCurrency0(financialSummary.revenue.baseRevenue - financialSummary.totalExpenses.total)}
                </small>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* PAYMENT SUMMARY SECTION */}
      <div className="report-summary" style={{ marginTop: '24px' }}>
        <h3>💳 Payment Summary</h3>
        <div className="summary-grid">
          <div className="summary-item">
            <Icon name="dollar-sign" size={24} />
            <div>
              <span>Total Billed</span>
              <strong>{formatCurrency0(filteredInvoices.reduce((sum, inv) => sum + (inv.grandTotal || 0), 0))}</strong>
              <small style={{ color: '#64748b', fontSize: '11px' }}>Total invoiced amount</small>
            </div>
          </div>

          <div className="summary-item" style={{ color: '#10b981' }}>
            <Icon name="check-circle" size={24} />
            <div>
              <span>Collected Amount</span>
              <strong>{formatCurrency0(reportData.paymentSummary.collected)}</strong>
              <small style={{ color: '#64748b', fontSize: '11px' }}>Cash received</small>
            </div>
          </div>

          {reportData.paymentSummary.pending > 0 && (
            <div className="summary-item" style={{ color: '#f59e0b' }}>
              <Icon name="clock" size={24} />
              <div>
                <span>Pending Amount</span>
                <strong>{formatCurrency0(reportData.paymentSummary.pending)}</strong>
                <small style={{ color: '#64748b', fontSize: '11px' }}>{reportData.paymentSummary.emiCount} EMI invoices</small>
              </div>
            </div>
          )}
        </div>
      </div>

      {/* BUSINESS OVERVIEW SECTION */}
      <div className="report-summary" style={{ marginTop: '24px' }}>
        <h3>📦 Business Overview</h3>
        <div className="summary-grid">
          <div className="summary-item">
            <Icon name="calendar" size={24} />
            <div>
              <span>Period</span>
              <strong>{reportData.period}</strong>
            </div>
          </div>

          <div className="summary-item">
            <Icon name="file-text" size={24} />
            <div>
              <span>Total Invoices</span>
              <strong>{reportData.totalInvoices}</strong>
            </div>
          </div>

          <div className="summary-item">
            <Icon name="package" size={24} />
            <div>
              <span>Total Products</span>
              <strong>{reportData.totalProducts}</strong>
            </div>
          </div>

          <div className="summary-item">
            <Icon name="users" size={24} />
            <div>
              <span>Total Customers</span>
              <strong>{reportData.totalCustomers}</strong>
            </div>
          </div>

          {reportData.lowStockCount > 0 && (
            <div className="summary-item" style={{ color: '#ef4444' }}>
              <Icon name="alert-triangle" size={24} />
              <div>
                <span>Low Stock Items</span>
                <strong>{reportData.lowStockCount}</strong>
                <small style={{ color: '#64748b', fontSize: '11px' }}>Need reorder</small>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
