"""
Automatic Salary Expense Generator
Runs periodically to create monthly salary expenses for active employees
"""

import logging
from datetime import datetime, timedelta
from calendar import monthrange
from bson import ObjectId

from database import get_db
from utils.tzutils import utc_now

logger = logging.getLogger(__name__)

def process_monthly_salaries():
    """
    Process monthly salaries for all active employees.

    Logic:
    1. Get all active employees
    2. For each employee, check if salary was already paid this month
    3. If NOT paid and salary_day has passed, create salary expense
    4. Prevent duplicates by checking existing salary entries for the month

    Returns:
        dict: Summary of processed salaries
    """
    try:
        db = get_db()
        now = utc_now()
        current_year = now.year
        current_month = now.month
        current_day = now.day

        # Get all active employees
        employees = list(db.employees.find({"is_active": True}))

        if not employees:
            logger.info("No active employees found")
            return {
                "success": True,
                "processed": 0,
                "skipped": 0,
                "message": "No active employees"
            }

        processed_count = 0
        skipped_count = 0
        errors = []

        for employee in employees:
            emp_id = employee['_id']
            salary_amount = employee.get('salary_amount')
            salary_day = employee.get('salary_day', 1)
            emp_name = employee.get('name')

            # Skip if no salary amount configured
            if not salary_amount or salary_amount <= 0:
                logger.warning(f"Employee {emp_name} has no salary configured")
                skipped_count += 1
                continue

            try:
                # Check if salary already exists for this month
                month_start = datetime(current_year, current_month, 1)
                month_end_day = monthrange(current_year, current_month)[1]
                month_end = datetime(current_year, current_month, month_end_day, 23, 59, 59)

                existing_salary = db.expenses.find_one({
                    "employee_id": emp_id,
                    "category": "salary",
                    "date": {
                        "$gte": month_start,
                        "$lte": month_end
                    }
                })

                if existing_salary:
                    logger.info(f"Salary already processed for {emp_name} in {current_month}/{current_year}")
                    skipped_count += 1
                    continue

                # Check if salary day has reached
                if current_day < salary_day:
                    logger.info(f"Salary day {salary_day} not reached for {emp_name}")
                    skipped_count += 1
                    continue

                # Create salary expense
                expense = {
                    "description": f"Salary - {emp_name} ({datetime(current_year, current_month, 1).strftime('%B %Y')})",
                    "amount": salary_amount,
                    "category": "salary",
                    "expenseType": "operational",
                    "employee_id": emp_id,
                    "date": now,
                    "createdAt": now,
                    "createdBy": None,  # System-generated
                    "createdByUsername": "SYSTEM",
                    "autoGenerated": True
                }

                result = db.expenses.insert_one(expense)

                logger.info(f"Salary expense created for {emp_name}: ₹{salary_amount}")
                processed_count += 1

            except Exception as e:
                error_msg = f"Error processing salary for {emp_name}: {str(e)}"
                logger.error(error_msg)
                errors.append(error_msg)
                skipped_count += 1

        return {
            "success": True,
            "processed": processed_count,
            "skipped": skipped_count,
            "errors": errors,
            "message": f"Processed {processed_count} salaries, skipped {skipped_count}"
        }

    except Exception as e:
        logger.error(f"Fatal error in process_monthly_salaries: {str(e)}")
        return {
            "success": False,
            "error": str(e),
            "message": "Failed to process monthly salaries"
        }

def check_salary_due():
    """
    Check which employees have salaries due today.

    Returns:
        list: Employees with salaries due
    """
    try:
        db = get_db()
        now = utc_now()
        current_day = now.day

        # Get employees with salary due today
        due_employees = list(db.employees.find({
            "is_active": True,
            "salary_day": current_day,
            "salary_amount": {"$gt": 0}
        }))

        return due_employees

    except Exception as e:
        logger.error(f"Error checking salary due: {str(e)}")
        return []

def get_salary_summary(employee_id=None):
    """
    Get salary payment summary for an employee or all employees.

    Args:
        employee_id: Optional employee ID to get summary for

    Returns:
        dict: Salary summary
    """
    try:
        db = get_db()

        if employee_id:
            try:
                emp_id = ObjectId(employee_id)
            except:
                return {"error": "Invalid employee ID"}

            employee = db.employees.find_one({"_id": emp_id})
            if not employee:
                return {"error": "Employee not found"}

            # Get salary expenses for this employee
            salaries = list(db.expenses.find({
                "employee_id": emp_id,
                "category": "salary"
            }).sort("date", -1).limit(12))  # Last 12 months

            total_paid = sum(s.get('amount', 0) for s in salaries)

            return {
                "employee": {
                    "id": str(emp_id),
                    "name": employee.get('name'),
                    "salaryAmount": employee.get('salary_amount'),
                    "salaryDay": employee.get('salary_day', 1)
                },
                "totalPaid": total_paid,
                "paymentCount": len(salaries),
                "lastPaymentDate": salaries[0].get('date').isoformat() if salaries else None
            }

        # Get summary for all employees
        employees = list(db.employees.find({"is_active": True}))
        summary = {
            "totalEmployees": len(employees),
            "monthlySalaryBudget": sum(e.get('salary_amount', 0) for e in employees),
            "employees": []
        }

        for emp in employees:
            emp_id = emp['_id']
            salaries = list(db.expenses.find({
                "employee_id": emp_id,
                "category": "salary"
            }).sort("date", -1).limit(1))

            summary["employees"].append({
                "id": str(emp_id),
                "name": emp.get('name'),
                "salaryAmount": emp.get('salary_amount'),
                "salaryDay": emp.get('salary_day', 1),
                "isActive": emp.get('is_active', True),
                "lastPaymentDate": salaries[0].get('date').isoformat() if salaries else None
            })

        return summary

    except Exception as e:
        logger.error(f"Error getting salary summary: {str(e)}")
        return {"error": str(e)}
